### Matrix aggregation

* Obtaining meaningful stats like mean, std, and sum of matrix 
* Helps in reducing dimensions of tensors

In [1]:
import torch

In [2]:
matrix = torch.tensor([[1.,2.,3.],
                      [1.,2.,3.],
                      [1.,2.,3.]])

In [3]:
print(matrix)

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])


In [5]:
matrix.sum()

tensor(18.)

In [6]:
matrix.mean()

tensor(2.)

In [8]:
matrix.median()

tensor(2.)

In [9]:
matrix.max()

tensor(3.)

In [ ]:
# aggregation across specific dimensions
# Column -> dim = 1 (across rows)
# row -> dim = 0 (across columns)

matrix.sum(dim=1)

tensor([6., 6., 6.])

In [12]:
matrix.sum(dim=0)

tensor([3., 6., 9.])

In [ ]:
matrix.cumsum(dim=1) # cumlative

tensor([[1., 3., 6.],
        [1., 3., 6.],
        [1., 3., 6.]])

In [14]:
# Advance Aggregation

matrix[matrix>1].sum()

tensor(15.)

In [ ]:
matrix.nonzero() # Gives the list of index of the non-zero elements in the matrix

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])

In [18]:
matrix.shape

torch.Size([3, 3])

In [19]:
max_val = matrix.max()
min_val = matrix.min()


normalized_matrix = (matrix - min_val) / (max_val - min_val)
print(normalized_matrix) 

tensor([[0.0000, 0.5000, 1.0000],
        [0.0000, 0.5000, 1.0000],
        [0.0000, 0.5000, 1.0000]])
