In [1]:
import torch

In [2]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,5,6])

In [7]:
print(tensor_1, tensor_2)

tensor([1, 2, 3]) tensor([4, 5, 6])


In [3]:
vstack = torch.stack((tensor_1, tensor_2), dim=0)

In [4]:
hstack = torch.stack((tensor_1, tensor_2), dim=1)

In [5]:
print(vstack)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [21]:
print(hstack) 
print(tensor_1.ndim)
print(hstack.ndim)# adds an extra dimension to the output tensor

tensor([[1, 4],
        [2, 5],
        [3, 6]])
1
2


In [9]:
# stacking 2d tensors

tensor2d_1 = torch.tensor([[1,2],[3,4]])
tensor2d_2 = torch.tensor([[5,6],[7,8]])

In [10]:
vstack2d = torch.stack((tensor2d_1, tensor2d_2), dim=0)

In [11]:
hstack2d = torch.stack((tensor2d_1, tensor2d_2), dim=1)

In [22]:
print(vstack2d)
print(tensor2d_1.ndim)
print(vstack2d.ndim)# adds an extra dimension to the output tensor

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
2
3


In [ ]:
print(hstack2d) # dim =1 of first tensor and dim=1 of second tensor are stacked into first row of the stacked tensor

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [ ]:
# concat

concatenated = torch.cat((tensor2d_1, tensor2d_2), dim=0) 

In [24]:
print(concatenated)
print(tensor2d_1.ndim)
print(concatenated.ndim)# does not add an extra dimension to the stacked tensor

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
2
2
