In [1]:
import torch

In [2]:
tensor = torch.arange(20)

In [4]:
reshaped_tensor = tensor.view(2,10)
reshaped_tensor_2 = tensor.reshape(2,10)

In [5]:
print(reshaped_tensor)
print(reshaped_tensor_2)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])


In [7]:
# check if contiguous

tensor.is_contiguous()

True

In [ ]:
# when no.of columns is unsure ( used in CNNs)
# -1 -> unsure
inferred_shape = tensor.view(2,-1)

In [10]:
inferred_shape

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [11]:
tensor3d = torch.arange(24).reshape(2,3,4)

In [12]:
tensor3d

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [13]:
# to pass to CNN
flattened_tensor = tensor.view(-1)
print(flattened_tensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


In [15]:
flattened_tensor.is_contiguous()

True

In [16]:
tensor3d = torch.arange(24).reshape(12,2)

In [17]:
transpose_3d = tensor3d.T

In [18]:
transpose_3d.is_contiguous()

False

In [19]:
## Trying view with non contiguous data

error = transpose_3d.view(6,4)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [20]:
reshaped_3d = transpose_3d.reshape(6,4)

In [21]:
reshaped_3d

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])