## Linear alzebra 2: Matix operations

In [1]:
import numpy as np

In [2]:
v  = np.array([1,3])

In [4]:
v

array([1, 3])

In [6]:
# flip over the x-axis

v = np.array([1, -3])
Ev = np.array([[1,0],[0,-1]])

v2 = np.dot(Ev, v)
v2

array([1, 3])

In [8]:
# scale by 2

v = np.array([1, 3])
Ev = np.array([[2,0],[0,2]])
v2 = np.dot(Ev, v)
v2

array([2, 6])

### Eigenvalues and Eigenvectors

In [9]:
# Eigenvectors are charateristic vectors of a matrix 
# A vector v is eigenvector if it maintains the same direction after transformation by A

# Eigenvalue is simply a scalar that scales the eigenvector
# A vector v is eigenvector of a matrix A if
# A*v = λ*v

A = np.array([[-1, 4], [2, -2]])

In [ ]:
# Eigenvalues and eigenvectors of a matirx A can be dervied using QR decomposition

### TODO LATER

In [11]:
lambdas, v = np.linalg.eig(A)

In [15]:
v # there are n no. of eigenvectors for a matrix with n columns (2 vectors for 2x2 matrix)

array([[ 0.86011126, -0.76454754],
       [ 0.51010647,  0.64456735]])

In [16]:
lambdas # there are n no. of eigenvalues for a matrix with n columns  (2 values for 2x2 matrix)

array([ 1.37228132, -4.37228132])

In [18]:
# confim that A*v = λ*v for each eigenvector

for i in range(len(lambdas)):
    lhs = A @ v[:,i]
    rhs = lambdas[i] * v[:,i]
    print(f"LHS = RHS: {lhs == rhs}") # @ is matrix multiplication and * is element-wise multiplication
    print("Eigenvalue: ", lambdas[i])
    print("Eigenvector: ", v[:, i])
    print()


LHS = RHS: [ True  True]
Eigenvalue:  1.3722813232690143
Eigenvector:  [0.86011126 0.51010647]

LHS = RHS: [ True  True]
Eigenvalue:  -4.372281323269014
Eigenvector:  [-0.76454754  0.64456735]



In [20]:
import torch

# torch.eig() is used to compute the eigenvalues and eigenvectors of a square matrix
# although it is deprecated in favor of torch.linalg.eig()
# it returns only the eigenvalues, not the eigenvectors
# set the parameter 'eigenvectors' to True to get the eigenvectors

A = torch.tensor([[-1, 4], [2, -2]], dtype=torch.float32)
eigenvalues, eigenvectors = torch.linalg.eig(A)
print("Eigenvalues: ", eigenvalues)

Eigenvalues:  tensor([ 1.3723+0.j, -4.3723+0.j])


In [21]:
eigenvectors

tensor([[ 0.8601+0.j, -0.7645+0.j],
        [ 0.5101+0.j,  0.6446+0.j]])

In [22]:
# Eigenvectors for more than 2 dimensions

A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

lambdas, v = np.linalg.eig(A)
print("Eigenvalues: ", lambdas)
print("Eigenvectors: ", v)

Eigenvalues:  [-5.2296696  -0.02635282  7.25602242]
Eigenvectors:  [[ 0.22578016 -0.75769839 -0.49927017]
 [ 0.52634845  0.63212771 -0.46674201]
 [-0.81974424 -0.16219652 -0.72998712]]


In [25]:
# Matrix determinant

# The determinant of a matrix is a scalar value that can be computed from the elements of a square matrix
# any matrix with det = 0 is singular and not invertible
A = np.array([[8, 2], [3, 4]])

det = np.linalg.det(A)
print("Determinant: ", det)

Determinant:  25.99999999999999


In [26]:
# Deteiminant of a 5x5 matrix

A = np.random.rand(5, 5)
det = np.linalg.det(A)
print("Determinant of 5x5 matrix: ", det)

Determinant of 5x5 matrix:  -0.0844630036697073


In [27]:
# general formula for determinant of an n x n matrix

# det(A) = a11 * det(A11) - a12 * det(A12) + a13 * det(A13) - ... + (-1)^(n+1) * a1n * det(A1n)

# where Aij is the matrix obtained by removing the ith row and jth column from A

print("Formula for determinant of n x n matrix: ")
print("det(A) = a11 * det(A11) - a12 * det(A12) + a13 * det(A13) - ... + (-1)^(n+1) * a1n * det(A1n)")

Formula for determinant of n x n matrix: 
det(A) = a11 * det(A11) - a12 * det(A12) + a13 * det(A13) - ... + (-1)^(n+1) * a1n * det(A1n)


In [28]:
# a det(x) is product of all the eigenvalues of the matrix
 
X = np.array([[1, 2], [3, 4]])

lambdas, v = np.linalg.eig(X)
det = np.prod(lambdas)

print("Determinant of X: ", det)
print("Eigenvalues of X: ", lambdas)
print("Product of eigenvalues: ", np.prod(lambdas))

Determinant of X:  -1.9999999999999998
Eigenvalues of X:  [-0.37228132  5.37228132]
Product of eigenvalues:  -1.9999999999999998


In [29]:
# Eigendecomposition

# Eigendecomposition is the process of decomposing a matrix into its eigenvalues and eigenvectors
# A = PDP^-1
# where P is the matrix of eigenvectors and D is the diagonal matrix of eigenvalues

In [30]:
A = np.array([[1, 2], [3, 4]])

# perform eigendecomposition

lambdas, v = np.linalg.eig(A)

D = np.diag(lambdas)
P = v
P_inv = np.linalg.inv(P)

A_reconstructed = P @ D @ P_inv
print("Reconstructed matrix: ")
print(A_reconstructed)

print("Original matrix: ")
print(A)

Reconstructed matrix: 
[[1. 2.]
 [3. 4.]]
Original matrix: 
[[1 2]
 [3 4]]


In [32]:
# SVD

# Todo later

In [33]:
# Compression of image using SVD

# Todo later

In [35]:
A = np.array([[1,2,],[3,4,],[5,6,]])

In [36]:
U, D, VT = np.linalg.svd(A)

In [37]:
U

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

In [38]:
VT

array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]])

In [39]:
D

array([9.52551809, 0.51430058])

### Moore-penrose pseudoinverse

In [40]:
D = np.diag(D)
D

array([[9.52551809, 0.        ],
       [0.        , 0.51430058]])

In [42]:
Dinv = np.linalg.inv(D)

In [43]:
Dinv

array([[0.10498117, 0.        ],
       [0.        , 1.94438824]])

In [44]:
Dplus = np.concatenate((Dinv, np.array([[0,0]]).T),axis=1)
Dplus

array([[0.10498117, 0.        , 0.        ],
       [0.        , 1.94438824, 0.        ]])

In [45]:
np.dot(VT.T, np.dot(Dplus, U.T))

array([[-1.33333333, -0.33333333,  0.66666667],
       [ 1.08333333,  0.33333333, -0.41666667]])

In [46]:
# numpy function for pseudoinverse

np.linalg.pinv(A)

array([[-1.33333333, -0.33333333,  0.66666667],
       [ 1.08333333,  0.33333333, -0.41666667]])